version = 0.1
[default.deploy.parameters]
stack_name = "CognitoPracticeStack"
resolve_s3 = true
s3_prefix = "CognitoPracticeStack"
region = "us-west-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "AppName=\"cog-practice-stack\" ClientDomains=\"http://localhost:8080,https://oauth.pstmn.io/v1/callback\" AdminEmail=\"seanoneill95@live.com\" SuperUserEmail=\"allinall99+superuser@gmail.com\" AddGroupsToScopes=\"true\""
image_repositories = []
